### PR TITLE
Fix iwconfig re_interface regex

### PR DESCRIPTION
**Pull request by six3six**
Small fix of re_interface in iwconfig.py.
When the network SSID contains a "-" character, the network interface was ignored.

### CODE REVIEW

**Comment by vrince** [comment]
Was about to fix it! encountered the same issue this morning ... Will drop my MR to keep this one.

**Comment by vrince** [comment]
Actually, I have no idea how "weird" ESSID could be, so I relax way more with the regex in my MR maybe it's gonna be a little bit more "future" proof? #386 What so you think?

**Comment by kellyjonbrazil** [comment]
Thanks for the fix! This is expectedly causing tests to fail, but I can merge this and fix them up as well as add a test case for SSIDs with a `-` character.

**Comment by kellyjonbrazil** [comment]
Oh sorry that was another PR causing tests to fail. It looks like the other PR was stripping fields, which is probably a good idea. I'll merge this and also add that functionality.

**Pull request merged**
