### PR TITLE
Fix #38, #39

### LINKED ISSUE #38: Footers not skipped in systemctl list-sockets parser
Footer lines are not being skipped.
```
…
 {
    "listen": "kobject-uevent",
    "unit": "1",
    "activates": "systemd-udevd-kernel.socket"
  },
  {
    "listen": "12",
    "unit": "sockets",
    "activates": "listed."
  },
  {
    "listen": "Pass",
    "unit": "--all",
    "activates": "to"
  }
]
```

### PR DESCRIPTION
**Pull request by philippeitis**
It seems that this magic() by matching the last valid parser in parser_info(), which seems problematic since it depends on the parsers being correctly sorted, which isn't validated. In this case, it seems like you may want to consider using a dictionary for your parser_info to do a simple lookup for the parser. -eg. 
```
if command in parser_info:
    found_parser = ...
elif args_given[0] in parser_info:
    found_parser = ...
```

### CODE REVIEW

**Comment by kellyjonbrazil** [comment]
Looks like this is working, thanks!

**Comment by philippeitis** [comment]
And an alternative implementation which uses a dictionary:
```
def magic():
    """Parse with magic syntax: jc -p ls -al"""
    if len(sys.argv) <= 1 or sys.argv[1].startswith('--'):
        return

    magic_dict = {}
    parser_info = about_jc()['parsers']
    # Create a dictionary to of magic_commands to their respective parsers.
    for parser in parser_info:
        if "magic_commands" in parser:
            magic_dict.update({magic_command: parser for magic_command in parser["magic_commands"]})

    # correctly parse escape characters and spaces with shlex
    args_given = " ".join(map(shlex.quote, sys.argv[1:])).split()
    options = []

    # find the options
    p = 0
    for i, arg in list(enumerate(args_given)):
        # parser found - use standard syntax
        if arg.startswith('--'):
            return
        # option found - populate option list
        elif arg.startswith('-'):
            options.append(args_given.pop(i - p)[1:])
            p += 1
        # command found if iterator didn't already stop - stop iterating
        else:
            break

    if len(args_given) == 0:
        return

    # find the command and parser
    command = ' '.join(args_given[0:2])
    # Try to get a parser for command, otherwise get one for args_given[0]
    parser = magic_dict.get(command, magic_dict.get(args_given[0]))
    # Get found_parser if a parser exists.
    found_parser = parser.get("argument") if parser else None
    
    # construct a new command line using the standard syntax: COMMAND | jc --PARSER -OPTIONS
    run_command = ' '.join(args_given)
    if found_parser:
        cmd_options = '-' + ''.join(options) if options else ''
        whole_command = ' '.join([run_command, '|', 'jc', found_parser, cmd_options])
        os.system(whole_command)
    else:
        helptext(f'parser not found for "{run_command}"')
        sys.exit(1)
```

**Comment by kellyjonbrazil** [comment]
I like the dictionary approach - it seems cleaner. I'll take a closer look at it and play around with it. Thanks!

**Comment by kellyjonbrazil** [comment]
I took your dictionary approach and slightly modified it and it seems to work well. I streamlined `magic_dict` so it simply contains the command as the key and the argument as the value. A couple other minor changes to simplify the code and increase readability. Still need to test this on linux... only tested on my Mac, which doesn't allow testing for `systemctl`. Let me know if you have any concerns about this.
```
def magic():
    """Parse with magic syntax: jc -p ls -al"""
    if len(sys.argv) <= 1 or sys.argv[1].startswith('--'):
        return

    magic_dict = {}
    parser_info = about_jc()['parsers']

    # Create a dictionary of magic_commands to their respective parsers.
    for entry in parser_info:
        # Update the dict with all of the magic commands for this parser, if they exist.
        magic_dict.update({mc: entry['argument'] for mc in entry.get('magic_commands', [])})

    # correctly parse escape characters and spaces with shlex
    args_given = " ".join(map(shlex.quote, sys.argv[1:])).split()
    options = []

    # find the options
    popped = 0
    for i, arg in list(enumerate(args_given)):
        # parser found - use standard syntax
        if arg.startswith('--'):
            return

        # option found - populate option list
        elif arg.startswith('-'):
            options.append(args_given.pop(i - popped)[1:])
            popped += 1

        # command found if iterator didn't already stop - stop iterating
        else:
            break

    # all options popped and no command found - for case like 'jc -a'
    if len(args_given) == 0:
        return

    # find the command and parser
    one_word_command = args_given[0]
    two_word_command = ' '.join(args_given[0:2])

    # Try to get a parser for two_word_command, otherwise get one for one_word_command
    found_parser = magic_dict.get(two_word_command, magic_dict.get(one_word_command))

    # construct a new command line using the standard syntax: COMMAND | jc --PARSER -OPTIONS
    run_command = ' '.join(args_given)
    if found_parser:
        cmd_options = '-' + ''.join(options) if options else ''
        whole_command = ' '.join([run_command, '|', 'jc', found_parser, cmd_options])
        os.system(whole_command)
        exit()

    else:
        helptext(f'parser not found for "{run_command}"')
        sys.exit(1)
```

**Comment by philippeitis** [comment]
I think it should be possible to add unit tests to actually run the commands on Linux if you're willing to look into installing the respective tools through a Github actions instance and then running automated tests against them and reading their input in to validate that they're correct.

**Comment by kellyjonbrazil** [comment]
I agree - was thinking about this. Will have to find commands that will have consistent output, though. Not sure how easy that will be to do in practice.

**Comment by kellyjonbrazil** [comment]
or maybe mock the commands? (make a systemctl list-unit-files command that outputs mock data) But not sure how easy it will be to put that into the path to override the real command.

**Comment by philippeitis** [comment]
I might even move the core magic logic out into it's own function that generates a command / returns None, and then have a subprocess call in main() - this is more direct and allows easy testing regardless of system.

**Comment by kellyjonbrazil** [comment]
Yes, that makes sense, so we are just unit testing the string output of magic() instead of integration testing the whole parsed output. Ok, I'll work on that. Thanks for the tip!

**Pull request closed without merging**
