### PR TITLE
Added `snapcraft` support.

### PR DESCRIPTION
**Pull request by don-rumata**
Hi!

I have decided to add `snap` support to your project.

How to build:
```bash
snapcraft
```

I used a separate virtual machine, because in addition to `snap`, `lxd` is also installed.

Links used:
https://snapcraft.io/docs/python-apps
https://snapcraft.io/docs/using-external-metadata
https://snapcraft.io/docs/python-plugin
https://snapcraft.io/docs/snapcraft-app-and-service-metadata
https://snapcraft.io/docs/snapcraft-yaml-reference

### CODE REVIEW

**Comment by kellyjonbrazil** [comment]
Will the snap have access to the plugin directory? Looks like this might be a challenge:

https://forum.snapcraft.io/t/accessing-xdg-config-home-of-the-host/9780/8
https://forum.snapcraft.io/t/setting-xdg-data-dirs-in-desktop-snaps/2173/4

**Comment by don-rumata** [comment]
Haven't checked that part out. I just builded, installed and ran it.

Could this be the solution to the problem? https://snapcraft.io/docs/home-interface and https://github.com/snapcrafters/obs-studio/blob/master/snap/snapcraft.yaml#L331

**Comment by kellyjonbrazil** [comment]
Seems like it should but then it says only non-hidden files can be accessed and the plugin folder is within a hidden folder. 😦

**Comment by don-rumata** [comment]
@kellyjonbrazil , can you test this?

```yaml
parts:
  jc:
    plugin: python
    source: .
    # pulled v1.17.2, `git describe`
    # source: https://github.com/kellyjonbrazil/jc
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(grep version= setup.py | cut -d '=' -f 2 | sed "s/,$// ; s/'//g")
      snapcraftctl set-grade "stable"
    plugs:
      # - home
      jc-plugins:
        interface: personal-files
        read:
          - $HOME/.local/share/jc"

apps:
  jc:
    command: bin/jc
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
      - jc-plugins
```

https://github.com/universal-ctags/ctags-snap/blob/master/snap/snapcraft.yaml
https://forum.snapcraft.io/t/accessing-hidden-files-from-home/28494/4

**Comment by don-rumata** [comment]
misclick, sorry. https://github.com/kellyjonbrazil/jc/pull/498/commits/49eae313b8744589b3652118d0239a55df7ef5f0

**Comment by kellyjonbrazil** [comment]
Yeah, I'll try it out!

**Comment by don-rumata** [comment]
@kellyjonbrazil , If you tell me how to test the plugin from a folder - I will test the function in my environment.

**Comment by kellyjonbrazil** [comment]
Hi - you can add the following test parser to your plugin directory:

```
"""jc - JSON Convert TEST PARSER"""

class info():
    version = '1.0'
    description = 'TEST PARSER'
    author = 'TEST AUTHOR'
    author_email = 'TEST EMAIL'
    compatible = ['linux']
    tags = ['command']

__version__ = info.version

def parse(data, raw, quiet):
    return {}
```

Then you can see if it shows up with the following:

```
jc -h | grep testparser
```

**Comment by don-rumata** [comment]
What am I doing wrong?

```
root@ubuntu-2004-clean-01:~# XDG_DATA_HOME=$HOME/.local/share

root@ubuntu-2004-clean-01:~# echo $XDG_DATA_HOME 
/root/.local/share

root@ubuntu-2004-clean-01:~# jc --version 
jc version:  1.24.0
python interpreter version:  3.10.9
python path:  /usr/local/bin/jc

https://github.com/kellyjonbrazil/jc
© 2019-2023 Kelly Brazil
root@ubuntu-2004-clean-01:~# which jc
/usr/local/bin/jc

root@ubuntu-2004-clean-01:~# cat ~/.local/share/jc/jcparsers/test-parser.py
"""jc - JSON Convert TEST PARSER"""

class info():
    version = '1.0'
    description = 'TEST PARSER'
    author = 'TEST AUTHOR'
    author_email = 'TEST EMAIL'
    compatible = ['linux']
    tags = ['command']

__version__ = info.version

def parse(data, raw, quiet):
    return {}

root@ubuntu-2004-clean-01:~# jc -h | grep testparser
root@ubuntu-2004-clean-01:~# 
```

**Comment by kellyjonbrazil** [comment]
Let me know if that's not working - I saw a note in my email but I don't see it here so just following up.

**Comment by don-rumata** [comment]
Done: https://github.com/kellyjonbrazil/jc/pull/512

**Comment by kellyjonbrazil** [comment]
Should I close this one out and use #512?

**Comment by don-rumata** [comment]
Probably yes. It's a continuation of the theme.

**Pull request closed without merging**
