### PR TITLE
add guix package info

### PR DESCRIPTION
**Pull request by wigust**

### CODE REVIEW

**Comment by kellyjonbrazil** [comment]
Hi - thanks for the contribution! I'm checking out guix now. Are you one of the package maintainers? I didn't notice JC on the guix packages pages.

**Comment by kellyjonbrazil** [comment]
I'm getting this in my Guix instance:

```
# guix install jc
guix install: error: jc: unknown package
```

Is there another repo it needs to connect to or will it just take time for the package to be available?

**Comment by wigust** [comment]
Hi.

> Are you one of the package maintainers? I didn't notice JC on the guix packages pages.

Yes, I maintain a set of packages for Guix.  I don't see jc on http://guix.gnu.org/packages/J/page/4 too, but it's on https://hpc.guix.info/package/jc . http://guix.gnu.org/packages requires a time to auto-regenerate, as far as I know.

> Is there another repo it needs to connect to or will it just take time for the package to be available?

It's in the main repo, but you need to invoke `guix pull` before install to get new package recipes, including jc.

**Comment by kellyjonbrazil** [comment]
Cool, that worked - thanks!

**Pull request merged**
